Repository amperity/gocd-vault-secrets, pull requests merged in 2019-12, with the labels that each got.

#29 start the vault client lease timer to correctly notice and renew leases
  CHANGELOG.md
  src/amperity/gocd/secret/vault/plugin.clj
Labels: bugfix

#30 Release 0.3.2
  CHANGELOG.md
  project.clj
  resources/plugin.xml
Labels: release

#28 Removed unused function
  src/amperity/gocd/secret/vault/util.clj
  test/amperity/gocd/secret/vault/plugin_test.clj
Labels: low priority, polish
